version: '3'
services:
  app:
    build: .
    volumes:
      - $PWD:/var/www/app
    depends_on:
      - elasticsearch
      - redis
      - sidekiq
    ports:
      - 3000:3000
    networks:
      - esnet
      - main
    environment:
      - VIRTUAL_HOST=word.kenforthewin.com
      - LETSENCRYPT_HOST=word.kenforthewin.com
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      - main
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  redis: 
    image: 'redis'
    networks:
      - main
  sidekiq:
    restart: always
    build: .
    depends_on:
      - elasticsearch
      - redis
    entrypoint:
      - sidekiq
    networks:
      - esnet
      - main
volumes:
  esdata:
  esdata2:
networks:
  esnet:
  main: